###
GET http://localhost:8080/

### Create a new post
POST http://localhost:8080/post
Content-Type: application/json

{
    "title": "Post title new",
    "content": "Post content new",
    "published": true,
    "userId": 1
}