-- CreateTablePost
CREATE TABLE Post (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    content LONGTEXT,
    published BOOLEAN NOT NULL DEFAULT false,
    userId INT NOT NULL
);

-- CreateTableUser
CREATE TABLE User (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('ADMIN', 'USER') NOT NULL DEFAULT 'USER'
);

-- CreateIndex
CREATE UNIQUE INDEX email_unique ON User (email);